chore: Refactor init files by removing previous config parser code pieces

diff --git a/recipes-nodes/reth/init b/recipes-nodes/reth/init
--- a/recipes-nodes/reth/init
+++ b/recipes-nodes/reth/init
@@ -18,13 +18,10 @@ LOGFILE=/var/log/reth.log
 RETH_USER=reth
 ETH_GROUP=eth
 RETH_DIR=/persistent/reth
+JWT_SECRET_FILE=/var/volatile/jwt.hex
 
 start() {
 	echo -n "Starting $DESC: "
-	# Source the setup.env file
-	if [ -f /usr/bin/setup_env.sh ]; then
-		source /usr/bin/setup_env.sh
-	fi
 
 	# Ensure the reth log file exists and has correct permissions
   	touch $LOGFILE
@@ -34,18 +31,18 @@ start() {
 	mkdir -p $RETH_DIR
 	chown $RETH_USER:$ETH_GROUP $RETH_DIR
 
-	# Set JWT_SECRET, use environment variable if set, otherwise use hardcoded value
-	JWT_SECRET=${JWT_SECRET:-"0x4c5a4856e3873434d51de798c8e4f17ca2dcc2ccd42cb72c8446db819fe69489"}
+	# Check if the JWT_SECRET_FILE exists and exit with a message if it doesn't
+	if [ ! -f $JWT_SECRET_FILE ]; then
+		echo "JWT secret file not found at $JWT_SECRET_FILE. Exiting."
+		exit 1
+	fi
 
-	mount -o remount,size=90% /var/volatile
-	echo "$JWT_SECRET" > /var/volatile/jwt.hex
-	chown ${RETH_USER}:${ETH_GROUP} /var/volatile/jwt.hex
 	start-stop-daemon -S --make-pidfile -p $PIDFILE -c $RETH_USER:$ETH_GROUP -N -10 -b -a /bin/sh -- -c "exec ${DAEMON} \
 		node \
 		--full \
 		--datadir "$RETH_DIR" \
 		--authrpc.addr 0.0.0.0 \
-		--authrpc.jwtsecret "/var/volatile/jwt.hex" \
+		--authrpc.jwtsecret "$JWT_SECRET_FILE" \
 		--authrpc.port 8551 \
 		--http \
 		--http.addr 0.0.0.0 \
